In [2]:
import pandas as pd

In [3]:
# reading head of the raw data
df = pd.read_csv("laptopData.csv")
df.head()

,Unnamed: 0,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [4]:
#first of all i wanna make the unnamed column into laptopn ID named
# Here how to do it 
df = df.rename(columns={"Unnamed: 0":'Laptop_ID'})
df.head()

,Laptop_ID,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1.0,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2.0,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0000
3,3.0,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.3360
4,4.0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.8080

In [5]:
# getting information of raw data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Laptop_ID         1273 non-null   float64
 1   Company           1273 non-null   str
 2   TypeName          1273 non-null   str
 3   Inches            1273 non-null   str
 4   ScreenResolution  1273 non-null   str
 5   Cpu               1273 non-null   str
 6   Ram               1273 non-null   str
 7   Memory            1273 non-null   str
 8   Gpu               1273 non-null   str
 9   OpSys             1273 non-null   str
 10  Weight            1273 non-null   str
 11  Price             1273 non-null   float64
dtypes: float64(2), str(10)
memory usage: 122.3 KB

In [6]:
# changing every column to desired datatype
# using build-in function
# i will use try-except to getting better error handling
try:
    df = df.convert_dtypes()
    display(df.dtypes)
    display(df.head())
except Exception as E:
    print("ERROR: ",E)

Laptop_ID             Int64
Company              string
TypeName             string
Inches               string
ScreenResolution     string
Cpu                  string
Ram                  string
Memory               string
Gpu                  string
OpSys                string
Weight               string
Price               Float64
dtype: object

,Laptop_ID,Company,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price
0,0,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,71378.6832
1,1,Apple,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,47895.5232
2,2,HP,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,30636.0
3,3,Apple,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,135195.336
4,4,Apple,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,96095.808

In [7]:
# now checking null values inside my data set
df.isnull().sum()

Laptop_ID           30
Company             30
TypeName            30
Inches              30
ScreenResolution    30
Cpu                 30
Ram                 30
Memory              30
Gpu                 30
OpSys               30
Weight              30
Price               30
dtype: int64

In [8]:
df['Laptop_ID'].isnull().sum()

np.int64(30)

In [9]:
df.columns

Index(['Laptop_ID', 'Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu',
       'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='str')

In [10]:
try:
    df['Company'].str.strip()

except Exception as E:
    display("Error: ",E)

In [11]:
try:
    df['Gpu'] = df['Gpu'].str.replace(' ','',regex=False)
    display(df['Gpu'].head())
except Exception as E:
    display("ERROR: ", E)

0    IntelIrisPlusGraphics640
1         IntelHDGraphics6000
2          IntelHDGraphics620
3             AMDRadeonPro455
4    IntelIrisPlusGraphics650
Name: Gpu, dtype: string

In [12]:
df.columns

Index(['Laptop_ID', 'Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu',
       'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='str')

In [13]:
try:
    df["Ram"] = df["Ram"].str.strip()
    display(df["Ram"])
except Exception as E:
    print("ERROR",E)

0        8GB
1        8GB
2        8GB
3       16GB
4        8GB
        ...
1298     4GB
1299    16GB
1300     2GB
1301     6GB
1302     4GB
Name: Ram, Length: 1303, dtype: string

In [14]:
df["Price"].isnull().sum()

np.int64(30)

In [19]:
df.columns

Index(['Laptop_ID', 'Company', 'TypeName', 'Inches', 'ScreenResolution', 'Cpu',
       'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight', 'Price'],
      dtype='str')

In [27]:
try:
    df['Weight'] = df['Weight'].str.replace('kg',' ',case=False).str.strip()
except Exception as E:
    print("ERROR:" ,E)

In [32]:
df['Weight'] = pd.to_numeric(df['Weight'],errors ='coerce')
df['Weight IN KG'] = df['Weight']

In [33]:
df.to_csv("LAPTOPDATA.csv")